import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, FileText, Check, Sun, Moon } from "lucide-react";
import { useEffect, useState } from "react";
import { useTheme } from "../hooks/use-theme";
import { getAccessToken } from "../lib/api";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "OfferDraft — Offer packages in 5 minutes" },
      { name: "description", content: "AI-powered offer package builder for real estate agents. Cover letters, document merging, branded PDFs — done in five minutes." },
      { property: "og:title", content: "OfferDraft — Offer packages in 5 minutes" },
      { property: "og:description", content: "AI-powered offer package builder for real estate agents." },
    ],
  }),
  component: Landing,
});

function Nav() {
  const [scrolled, setScrolled] = useState(false);
  const { theme, toggle } = useTheme();
  useEffect(() => {
    const f = () => setScrolled(window.scrollY > 60);
    window.addEventListener("scroll", f);
    return () => window.removeEventListener("scroll", f);
  }, []);
  return (
    <nav
      className={`sticky top-0 z-40 px-6 lg:px-12 py-4 flex items-center justify-between transition-all ${
        scrolled ? "border-b border-[var(--color-border)] backdrop-blur bg-[rgba(30,30,30,0.88)]" : ""
      }`}
    >
      <Link to="/" className="serif text-2xl text-[var(--color-accent)]">OfferDraft</Link>
      <div className="flex items-center gap-2">
        {getAccessToken() ? (
          <Link to="/dashboard" className="btn-primary !py-2 !px-4 text-sm">Dashboard</Link>
        ) : (
          <>
            <Link to="/login" className="btn-ghost !py-2 !px-4 text-sm">Log in</Link>
            <Link to="/register" className="btn-primary !py-2 !px-4 text-sm">Get Started</Link>
          </>
        )}
        <button
          onClick={toggle}
          aria-label="Toggle theme"
          className="ml-1 w-8 h-8 rounded-lg flex items-center justify-center text-[var(--color-text-sec)] hover:text-[var(--color-text-pri)] hover:bg-[var(--color-surface)] border border-[var(--color-border)] transition-colors"
        >
          {theme === "dark" ? <Sun size={14} /> : <Moon size={14} />}
        </button>
      </div>
    </nav>
  );
}

function PdfMock() {
  return (
    <div className="card p-8 w-full max-w-[420px]">
      <div className="flex items-center justify-between pb-6 border-b border-[var(--color-border)]">
        <div className="w-12 h-12 rounded bg-[var(--color-accent-dim)] flex items-center justify-center serif text-[var(--color-accent)] text-xl">MR</div>
        <div className="label-xs">Offer Package</div>
      </div>
      <div className="mt-6">
        <div className="label-xs">Property</div>
        <div className="text-lg mt-1">142 Maple Street, Austin TX</div>
      </div>
      <div className="mt-5">
        <div className="label-xs">Offer Amount</div>
        <div className="mono text-3xl text-[var(--color-accent)] mt-1">$485,000</div>
      </div>
      <div className="mt-5 grid grid-cols-2 gap-4 text-sm">
        <div>
          <div className="label-xs">Closing</div>
          <div className="mt-1">Jul 28, 2026</div>
        </div>
        <div>
          <div className="label-xs">Loan</div>
          <div className="mt-1">Conventional</div>
        </div>
      </div>
      <div className="mt-8 pt-4 border-t border-[var(--color-border)] text-xs text-[var(--color-text-sec)] text-center">
        Generated by OfferDraft
      </div>
    </div>
  );
}

function Landing() {
  return (
    <div>
      <Nav />

      {/* Hero */}
      <section className="px-6 lg:px-12 pt-20 pb-32 max-w-[1200px] mx-auto grid lg:grid-cols-2 gap-16 items-center">
        <div>
          <div className="label-xs text-[var(--color-accent)]">Offer Packages</div>
          <h1 className="serif text-5xl lg:text-[64px] leading-[1.05] mt-5">
            Stop spending two hours on every offer package.
          </h1>
          <p className="mt-6 text-lg text-[var(--color-text-sec)] max-w-lg">
            OfferDraft writes the buyer cover letter, assembles your documents, and exports a branded PDF — ready in five minutes.
          </p>
          <div className="flex flex-wrap gap-3 mt-8">
            <Link to="/register" className="btn-primary !px-6 !py-3 text-base">
              Start Free Trial <ArrowRight size={16} />
            </Link>
            <a href="#workflow" className="btn-ghost !px-6 !py-3 text-base">See how it works</a>
          </div>
          <p className="mt-4 text-sm text-[var(--color-text-sec)]">No credit card required · Cancel anytime</p>
        </div>
        <div className="flex justify-center lg:justify-end">
          <PdfMock />
        </div>
      </section>

      {/* Pain points */}
      <section className="border-y border-[var(--color-border)]">
        <div className="max-w-[1200px] mx-auto grid grid-cols-1 md:grid-cols-3 divide-y md:divide-y-0 md:divide-x divide-[var(--color-border)]">
          {[
            { n: "2 hrs", t: "Per offer package, manually assembled" },
            { n: "3 docs", t: "Merged into one PDF automatically" },
            { n: "$0", t: "Extra staff needed to handle the admin" },
          ].map((p) => (
            <div key={p.n} className="px-10 py-12">
              <div className="serif italic text-5xl text-[var(--color-accent)] opacity-80">{p.n}</div>
              <div className="mt-4 text-[var(--color-text-sec)]">{p.t}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Workflow */}
      <section id="workflow" className="px-6 lg:px-12 py-24 max-w-[1200px] mx-auto">
        <div className="label-xs">The Workflow</div>
        <h2 className="serif text-4xl mt-3">Four steps. One PDF.</h2>

        <div className="mt-16 grid grid-cols-1 md:grid-cols-4 gap-8">
          {[
            "Enter property + offer details",
            "Upload buyer documents",
            "AI drafts the cover letter",
            "Download the complete package",
          ].map((step, i) => (
            <div key={i} className="relative">
              <div className="flex items-center gap-3">
                <div className="w-9 h-9 rounded-full border border-[var(--color-accent)] bg-[var(--color-accent-dim)] text-[var(--color-accent)] flex items-center justify-center text-sm font-semibold">{i + 1}</div>
                {i < 3 && <div className="hidden md:block flex-1 h-px bg-[var(--color-border)]" />}
              </div>
              <div className="mt-4 font-medium">{step}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Pricing teaser */}
      <section className="px-6 lg:px-12 py-20 max-w-[1200px] mx-auto">
        <div className="grid md:grid-cols-2 gap-6">
          {[
            { name: "Solo", price: "$49", desc: "1 agent · 30 packages/month", border: false },
            { name: "Team", price: "$149", desc: "5 agents · unlimited packages · white-label PDF", border: true },
          ].map((p) => (
            <div
              key={p.name}
              className="card p-8 flex flex-col"
              style={p.border ? { borderRightColor: "var(--color-accent)", borderRightWidth: 3 } : {}}
            >
              <div className="serif text-3xl">{p.name}</div>
              <div className="mt-3 mono text-3xl text-[var(--color-accent)]">{p.price}<span className="text-base text-[var(--color-text-sec)]">/mo</span></div>
              <div className="mt-3 text-[var(--color-text-sec)]">{p.desc}</div>
              <Link to="/pricing" className="btn-ghost mt-6 self-start">View plan details <ArrowRight size={14} /></Link>
            </div>
          ))}
        </div>
      </section>

      {/* Final CTA */}
      <section className="border-t border-[var(--color-border)] px-6 lg:px-12 py-24">
        <div className="max-w-[800px] mx-auto text-center">
          <h2 className="serif text-4xl lg:text-5xl">Your next offer is due in an hour.</h2>
          <p className="mt-4 text-lg text-[var(--color-text-sec)]">Build the package in five minutes.</p>
          <Link to="/register" className="btn-primary !px-6 !py-3 text-base mt-8 inline-flex">Get started free <ArrowRight size={16} /></Link>
        </div>
      </section>

      <footer className="border-t border-[var(--color-border)] px-6 lg:px-12 py-12">
        <div className="max-w-[1200px] mx-auto flex flex-col md:flex-row justify-between gap-8">
          <div>
            <div className="serif text-xl text-[var(--color-accent)]">OfferDraft</div>
            <div className="text-sm text-[var(--color-text-sec)] mt-2">Offer packages in 5 minutes.</div>
          </div>
          <div className="flex gap-6 text-sm text-[var(--color-text-sec)]">
            <Link to="/pricing" className="hover:text-[var(--color-text-pri)]">Pricing</Link>
            <Link to="/login" className="hover:text-[var(--color-text-pri)]">Login</Link>
            <a className="hover:text-[var(--color-text-pri)]" href="#">Terms</a>
            <a className="hover:text-[var(--color-text-pri)]" href="#">Privacy</a>
          </div>
        </div>
        <div className="max-w-[1200px] mx-auto mt-8 text-xs text-[var(--color-text-sec)]">© 2026 OfferDraft</div>
      </footer>
    </div>
  );
}

// silence unused
void FileText;
void Check;
